name: Passing Values to Next Steps & NEXT Jobs

on:  workflow_dispatch

jobs:
  passing-values-bw-steps:
    runs-on: ubuntu-latest
    steps:
    - name: Set the value using ENV Vars
      run: |
        echo "variableName=this-is-value" >> $GITHUB_ENV


    - name: Create-Variables
      id: var_source_step
      run: |
        echo "Performing a random task"
        echo "::set-output name=var1_name::TechSckool"
        echo "::set-output name=var2_date::$(date +'%Y-%m-%d-%H-%M')"
    

    - name: Get-Variable-Value
      run: |
        echo "Printing the values"
        echo variableName: ${{ env.variableName }} 
        echo var1_name: ${{ steps.var_source_step.outputs.var1_name }} 
        echo var2_date: ${{ steps.var_source_step.outputs.var2_date }}

    - name: Set output with new syntax
      run: echo "date_var=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
    
    - name: Get-output
      run: |
        echo "Printing the values with new syntax"
        echo "${{ env.date_var }}"

  job1:
    runs-on: windows-latest
    
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

    steps:
      - id: step1
        run: echo "::set-output name=test::ImportantValue1"
      - id: step2
        run: echo "::set-output name=test::ImportantValue2"
  
  
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Printing the values"
          echo output1: ${{needs.job1.outputs.output1}}
          echo output2: ${{needs.job1.outputs.output2}}
      - id: step2
        run: echo "test_job=ImportantValue1" >>$GITHUB_OUTPUT

  jobs3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: |
          echo "Printing the values from new syntax"
          echo output1: ${{env.test_job}}
