
name: 'self hosted runner demo'

on: workflow_dispatch

jobs:
  hello-self-hosted-runner:
    runs-on: [self-hosted, Linux, first-runner]
    steps: 
    - name: run-inside-self-hosted-runner
      run:  echo "From GitHub runners `hostname`"

    - name: sleep for 100 seconds
      run: sleep 100