name: Fetching secrets from github secret repository

on:
  workflow_dispatch

jobs:
  secret_repo:
    runs-on: ubuntu-latest

    steps:
        - name: Fetching secrets
          run: echo "My Secret ${{secret.ACTION_SECRET}}"